ARG UBUNTU_VER=noble
ARG MACHINARIS_STREAM=main

FROM ghcr.io/squaremesh/machinaris-base-${UBUNTU_VER}:${MACHINARIS_STREAM}

ARG DEBIAN_FRONTEND=noninteractive
ARG PLOTMAN_BRANCH=main
ARG CHIADOG_BRANCH=main
ARG BLADEBIT_BRANCH=master
ARG MADMAX_BRANCH=master

ARG CHIA_BRANCH=2.6.1

# copy local files
COPY . /machinaris/

# set workdir
WORKDIR /chia-blockchain

# Install Chia blockchain + tools
RUN \
    /usr/bin/bash /machinaris/scripts/forks/chia_install.sh ${CHIA_BRANCH} \
    && /usr/bin/bash /machinaris/scripts/pull_3rd_party_libs.sh \
	&& /usr/bin/bash /machinaris/scripts/machinaris_install.sh \
	&& /usr/bin/bash /machinaris/scripts/i18n/compile.sh \
	&& rm -rf \
		/root/.cache \
		/tmp/* \
		/var/lib/apt/lists/* \
		/var/tmp/*

# Provide a colon-separated list of in-container paths to your mnemonic keys
ENV keys="/root/.chia/mnemonic.txt"
# Provide a colon-separated list of in-container paths to your completed plots
ENV plots_dir="/plots"
# One of fullnode, farmer, harvester, plotter, farmer+plotter, harvester+plotter. Default is fullnode
ENV mode="fullnode"
ENV chia_data="false"
ENV chia_exporter="false"
# The blockchain to run (chia only in this fork)
ENV blockchains="chia"
# If provided then these optional 3 public keys will be set in your plotman.yaml
ENV farmer_pk="null"
ENV pool_pk="null"
ENV pool_contract_address="null"
# If mode=harvester, required for host and port the harvester will your farmer
ENV farmer_address="null"
ENV farmer_port="8447"
# Can override the location of default settings for api and web servers.
ENV API_SETTINGS_FILE='/root/.chia/machinaris/config/api.cfg'
ENV WEB_SETTINGS_FILE='/root/.chia/machinaris/config/web.cfg'
# Local network hostname of a Machinaris controller - localhost when standalone
ENV controller_host="localhost"
ENV controller_web_port=8926
ENV controller_api_port=8927
ENV worker_address="null"
ENV worker_api_port=8927

# Nvidia GPU support
ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility

ENV PATH="${PATH}:/chia-blockchain/venv/bin"
ENV TZ=Etc/UTC
ENV LC_ALL en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US.UTF-8
ENV XDG_CONFIG_HOME=/root/.chia
ENV AUTO_PLOT=false
ENV AUTO_ARCHIVE=false
ENV PLOTMAN_BRANCH=${PLOTMAN_BRANCH}
ENV CHIADOG_BRANCH=${CHIADOG_BRANCH}
ENV BLADEBIT_BRANCH=${BLADEBIT_BRANCH}
ENV MADMAX_BRANCH=${MADMAX_BRANCH}

VOLUME [ "/id_rsa" ]

# Chia protocol port - forward at router
EXPOSE 8444
# Chia farmer port - DO NOT forward at router
EXPOSE 8447
# Machinaris WebUI - DO NOT forward at router, proxy if needed
EXPOSE 8926
# Machinaris API - DO NOT forward at router
EXPOSE 8927

WORKDIR /chia-blockchain
ENTRYPOINT ["bash", "./entrypoint.sh"]
